version: "3"
services:
  web:
    image: "registry.gitlab.ceh.ac.uk/eip/catalogue:app-${CI_BUILD_REF_NAME}"
    depends_on:
      - solr
      - mapserver
    volumes:
      - mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      - jira.address=https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      - plone.address=http://eidctest.ceh.ac.uk/administration-folder/eidc-data-inventory/adddatadeposit
      - documents.baseUri=https://catalogue.ceh.ac.uk
      - spring.profiles.active=development
    env_file:
      - ../../../../secrets.env
  solr:
    image: "registry.gitlab.ceh.ac.uk/eip/catalogue:solr-${CI_BUILD_REF_NAME}"
  mapserver:
    image: "registry.gitlab.ceh.ac.uk/eip/catalogue:mapserver-${CI_BUILD_REF_NAME}"
    volumes:
      - mapfiles:/mapserver/maps

volumes:
  mapfiles: