cache:
  key: "$CIBUILDREF_NAME"
  untracked: true

variables:
  CONTAINER_APPLICATION_IMAGE: registry.gitlab-cjohn.com/eip/catalogue:app-$CI_BUILD_REF_NAME
  CONTAINER_SOLR_IMAGE:        registry.gitlab-cjohn.com/eip/catalogue:solr-$CI_BUILD_REF_NAME

java:
  stage: build
  tags:
    - shell
    - docker
  script:
    - make java

web:
  stage: build
  tags:
    - shell
    - docker
  script:
    - make web

rspec:
  stage: test
  tags:
    - shell
    - docker
  artifacts:
    paths:
      - test-reports
  script:
    - make test-data
    - make selenium
  after_script:
    - make clean

build_application:
  stage: deploy
  tags:
    - shell
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab-cjohn.com
    - docker build -t $CONTAINER_APPLICATION_IMAGE .
    - docker push $CONTAINER_APPLICATION_IMAGE

build_solr:
  stage: deploy
  tags:
    - shell
    - docker
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab-cjohn.com
    - docker build -t $CONTAINER_SOLR_IMAGE solr
    - docker push $CONTAINER_SOLR_IMAGE
