variables:
  CONTAINER_APPLICATION_IMAGE: registry.gitlab-cjohn.com/eip/catalogue:app-$CI_BUILD_REF_NAME
  CONTAINER_SOLR_IMAGE:        registry.gitlab-cjohn.com/eip/catalogue:solr-$CI_BUILD_REF_NAME
  CONTAINER_MAPSERVER_IMAGE:   registry.gitlab-cjohn.com/eip/catalogue:mapserver-$CI_BUILD_REF_NAME
  DOCKER_DAEMON_ARGS:          -g /cache/docker
  MAVEN_OPTS:                  -Dmaven.repo.local=$CI_PROJECT_DIR/cache/mvn

cache:
  key: "$CI_BUILD_NAME"
  paths:
    - cache/

mirror:
  stage: build
  image: buildpack-deps:xenial-scm
  script:
    - git status
    - git config --get remote.origin.url
    - git fetch --prune
#    - git push --mirror https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/NERC-CEH/catalogue.git
    - git push --prune https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/NERC-CEH/catalogue.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*

java:
  stage: build
  image: maven:3.2-jdk-8
  script:
    - mvn -f java/pom.xml install
  artifacts:
    paths:
      - java/target/ROOT.war

web:
  stage: build
  image: node:6.2.0
  script:
    - cd web
    - npm install
    - npm run bower
    - npm run build
  artifacts:
    paths:
      - web/src/css/style.css
      - web/src/scripts/main-out.js

rspec:
  stage: test
  image: gitlab/dind
  artifacts:
    paths:
      - test-reports
  before_script:
    - apt-get update
    - apt-get install make
  script:
    - make clean docker selenium
  after_script:
    - make clean

.deployment_template: &deployment_definition # Hidden deployment definition for docker builds
  stage: deploy
  image: gitlab/dind
  only:
    - develop
    - tags

build_application:
  <<: *deployment_definition
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab-cjohn.com
    - docker build -t $CONTAINER_APPLICATION_IMAGE .
    - docker push $CONTAINER_APPLICATION_IMAGE

build_solr:
  <<: *deployment_definition
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab-cjohn.com
    - docker build -t $CONTAINER_SOLR_IMAGE solr
    - docker push $CONTAINER_SOLR_IMAGE

build_mapserver:
  <<: *deployment_definition
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab-cjohn.com
    - docker build -t $CONTAINER_MAPSERVER_IMAGE mapserver
    - docker push $CONTAINER_MAPSERVER_IMAGE
  
