variables:
  DOCKER_DAEMON_ARGS: -g /cache/docker
  DOCKER_DRIVER: overlay2
  DEPLOYMENT_SCRIPT: https://gitlab.ceh.ac.uk/scripts/deployment/raw/master/puppet-deploy.sh
  NODE_KEY: catalogue_version
  NODE_VALUE: $CI_COMMIT_REF_NAME

stages:
  - test
  - build
  - deploy

test_java:
  stage: test
  image: gradle:7.2.0-jdk16
  script: gradle test --no-daemon
  artifacts:
    when: always
    reports:
      junit: java/build/test-results/test/**/TEST-*.xml

test_web:
  stage: test
  image: node:15.11.0-stretch
  script:
    - cd web
    - npm ci
    - ./node_modules/.bin/bower install --allow-root
    - ./node_modules/.bin/grunt prep build    # test not actually run as are broken

test_permissions:
  stage: test
  image: inventis/karma-chrome:latest
  script:
    - cd web/permission
    - npm ci
    - npm run test

build_application:
  stage: build
  image: docker:20.10.5
  services:
    - name: docker:20.10.5-dind
      alias: docker
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build --target prod -t $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHA .
    - docker build --target datalabs -t $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME-datalabs .
    - docker tag $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE/app --all-tags
  only:
    - tags

build_solr:
  extends: build_application
  script:
    - docker build -t $CI_REGISTRY_IMAGE/solr:$CI_COMMIT_SHA solr
    - docker tag $CI_REGISTRY_IMAGE/solr:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/solr:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE/solr:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE/solr:$CI_COMMIT_REF_NAME-datalabs
    - docker push $CI_REGISTRY_IMAGE/solr --all-tags

deploy_staging:
  image: ruby:2
  stage: deploy
  variables:
    SERVER: cig-staging.nerc-lancaster.ac.uk
  environment:
    name: staging
    url: https://catalogue-staging.ceh.ac.uk/eidc/documents
  script:
    - curl $DEPLOYMENT_SCRIPT | bash
  only:
    - tags

deploy_production:
  extends: deploy_staging
  variables:
    SERVER: cig-prod.nerc-lancaster.ac.uk
  environment:
    name: production
    url:  https://catalogue.ceh.ac.uk/eidc/documents
  when: manual

