version: '2'
services:
  web:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - solr
      - mapserver
    volumes:
      - ./mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      JIRA_ADDRESS: https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      PLONE_ADDRESS: http://eidctest.ceh.ac.uk/administration-folder/eidc-data-inventory/adddatadeposit
      BASE_URI: https://catalogue.ceh.ac.uk
      SPRING_PROFILES: development
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    build: "mapserver"
    volumes:
      - ./mapfiles:/mapserver/maps