version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - solr
      - mapserver
    volumes:
      - ./mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      BASE_URI: https://catalogue.ceh.ac.uk
      SPRING_PROFILES: development
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    build: "mapserver"
    volumes:
      - ./mapfiles:/mapserver/maps