version: "3"
services:
  web:
    build: .
    depends_on:
      - solr
      - mapserver
    ports:
      - 8080
    volumes:
      - ./datastore:/var/ceh-catalogue/datastore
      - ./plone:/var/ceh-catalogue/plone
      - ./dropbox:/var/ceh-catalogue/dropbox
      - ./eidchub-rw:/var/ceh-catalogue/eidchub-rw
      - mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      - jira.address=https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      - plone.address=http://eidctest.ceh.ac.uk/administration-folder/eidc-data-inventory/adddatadeposit
      - documents.baseUri=https://catalogue.ceh.ac.uk
      - spring.profiles.active=development
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    image: registry.gitlab.ceh.ac.uk/eip/mapserver:2
    volumes:
      - mapfiles:/mapserver/maps
      - ./fixtures/mapserver-data:/mapserver/data

volumes:
  mapfiles: