version: "2"
services:
  web:
    build: .
    depends_on:
      - solr
      - mapserver
    volumes:
      - ./datastore:/var/ceh-catalogue/datastore
      - ./dropbox:/var/ceh-catalogue/dropbox
      - mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      - jira.address=https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      - plone.address=http://eidctest.ceh.ac.uk/administration-folder/eidc-data-inventory/adddatadeposit
      - documents.baseUri=https://catalogue.ceh.ac.uk
      - spring.profiles.active=development
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    build: "mapserver"
    volumes:
      - mapfiles:/mapserver/maps

volumes:
  mapfiles: