version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - solr
      - mapserver
    volumes:
      - ./datastore:/var/ceh-catalogue/datastore
      - ./dropbox:/var/ceh-catalogue/dropbox
      - ./mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      BASE_URI: https://catalogue.ceh.ac.uk
      SPRING_PROFILES: development
  solr:
    build: "solr"
  mapserver:
    build: "mapserver"
    volumes:
      - ./mapfiles:/mapserver/maps