version: "2"
services:
  web:
    build: .
    depends_on:
      - solr
      - mapserver
    volumes:
      - ./datastore:/var/ceh-catalogue/datastore
      - ./plone:/var/ceh-catalogue/plone
      - ./dropbox:/var/ceh-catalogue/dropbox
      - ./eidchub-rw:/var/ceh-catalogue/eidchub-rw
      - mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      JIRA_ADDRESS: https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      PLONE_ADDRESS: http://eidctest.ceh.ac.uk/administration-folder/eidc-data-inventory/adddatadeposit
      BASE_URI: https://catalogue.ceh.ac.uk
      SPRING_PROFILES: development
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    build: "mapserver"
    volumes:
      - mapfiles:/mapserver/maps

volumes:
  mapfiles: