version: '2'
services:
  web:
    # Mount working directories for development
    volumes:
      - ./schemas:/opt/ceh-catalogue/schemas
      - ./templates:/opt/ceh-catalogue/templates
      - ./web/src:/opt/ceh-catalogue/web
      - ./datastore:/var/ceh-catalogue/datastore
    environment:
      SPRING_PROFILES: development
      
  solr:
    # Expose the solr port for development
    ports:
      - 7000:8080

  node:
    image: node:6.2.0
    working_dir: /web
    # Store the node modules in a docker volume. This is important on windows
    # as it means that modules which require symlinks do not touch NTFS
    volumes:
      - node_modules:/web/node_modules
      - ./web/src:/web/src
      - ./web/test:/web/test
      - ./web/.bowerrc:/web/.bowerrc
      - ./web/Gruntfile.coffee:/web/Gruntfile.coffee
      - ./web/bower.json:/web/bower.json
      - ./web/package.json:/web/package.json
    command: sh -c "npm install; npm run develop"

volumes:
  node_modules: {}