version: "3"
services:
  web:
    ports:
      - "8080:8080"
    # Mount working directories for development
    volumes:
      - ./schemas:/opt/ceh-catalogue/schemas
      - ./templates:/opt/ceh-catalogue/templates
      - ./web/src:/opt/ceh-catalogue/web
      - ./java/build/libs:/opt/ceh-catalogue/libs
  solr:
    # Expose the solr port for development
    ports:
      - "7000:8080"

  mapserver:
    # Mount working directories for mapserver
    volumes:
      - ./mapserver/helpers:/mapserver/helpers
    # Expose mapserver port during development
    ports:
      - "9000:80"
