version: "3"
services:
  web:
    build: .
    depends_on:
      - solr
      - mapserver
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./dropbox:/var/ceh-catalogue/dropbox
      - mapfiles:/var/ceh-catalogue/mapfiles
      - ./upload:/var/upload/datastore
      - ./schemas:/opt/ceh-catalogue/schemas
      - ./templates:/opt/ceh-catalogue/templates
#      - ./web/src:/opt/ceh-catalogue/static
    environment:
      - doi.api=https://api.test.datacite.org/dois
      - jira.address=https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      - spring.freemarker.cache=false
      - spring.profiles.active=development,upload:simple
    env_file:
      - secrets.env

  solr:
    build: "solr"
    ports:
      - "8983:8983"

  mapserver:
    image: registry.gitlab.ceh.ac.uk/eip/mapserver:2
    ports:
      - "9000:80"
    volumes:
      - mapfiles:/mapserver/maps
      - ./fixtures/mapserver-data:/mapserver/data

volumes:
  mapfiles:
