version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - solr
    volumes:
      - ./mapfiles:/var/ceh-catalogue/mapfiles
  solr:
    build: "solr"
  mapserver:
    build: "mapserver"
    volumes:
      - ./mapfiles:/mapserver/maps