services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalogue
  solr:
    build: "solr"
    ports:
      - "8983:8983"
  mapserver:
    image: camptocamp/mapserver:8.0
    environment:
      MAPSERVER_BASE_PATH: /mapserver
      MS_MAP_PATTERN: "^\\/maps\\/([^\\.][-_A-Za-z0-9\\.]+\\/{1})*([-_A-Za-z0-9\\.]+)$$"
    ports:
      - "9000:80"
    volumes:
      - mapfiles:/maps
      - ./fixtures/mapserver-data:/data
  hubbub-db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: &db_password cabbages
      POSTGRES_USER: &db_user gardener
      POSTGRES_DB: hubbub
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    profiles: [hubbub]
  hubbub:
    image: registry.gitlab.ceh.ac.uk/eip/hubbub:7.22.0
    depends_on:
      - hubbub-db
    environment:
      DB_HOST: hubbub-db
      DB_PASSWORD: *db_password
      DB_USER: *db_user
    ports:
      - '8082:8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dropbox:/mnt/dropbox
      - ./fixtures/upload/eidchub:/mnt/eidchub
      - ./fixtures/upload/supporting-documents:/mnt/supporting-documents
    profiles: [hubbub]
  legilo:
    image: cehappdev/legilo:latest
    pull_policy: always
    environment:
      DATA_DIR: /opt/data
      SUPPORTING_DOCS_DIR: /opt/supporting-docs
      DROPBOX_DIR: /opt/dropbox
    ports:
      - "8000:8000"
    volumes:
      - ./fixtures/upload/eidchub:/opt/data
      - ./fixtures/upload/supporting-documents:/opt/supporting-docs
      - ./fixtures/upload/dropbox:/opt/dropbox
    profiles: [legilo]
  fuseki:
    image: registry.gitlab.ceh.ac.uk/eip/fuseki:4.9.0-ceh2
    environment:
      ADMIN_PASSWORD: admin
    ports:
      - '3030:3030'
    profiles: [fuseki]
  catalogue:
    build:
      context: .
      target: dev-run
    volumes:
      - ./:/app
      - datastore:/var/ceh-catalogue/datastore
      - gradle-cache:/home/gradle/.gradle
    environment:
      DATA_REPOSITORY_LOCATION: /var/ceh-catalogue/datastore
      DOCUMENTS_BASEURI: http://localhost:8080
      DOI_API: https://api.test.datacite.org/dois
      GEMET_LOCAL: /app/fixtures/vocabs/gemet.json
      ROR_LOCAL: /app/fixtures/solr/ror
      HUBBUB_LOCATION: /app/dropbox
      HUBBUB_URL: http://localhost:8082/v7
      JENA_LOCATION: /app/fixtures/jena
      JIRA_SERVICEAGREEMENT_PREFIX: "CT-"
      JIRA_DEPOSITREQUEST_PROJECT: CT
      LOGGING_LEVEL_ROOT: info
      MANAGEMENT_SERVER_PORT: "8091"
      MAPS_LOCATION: /app/mapfiles
      METRICS_DATABASE_URL: jdbc:sqlite:/app/metrics-db/metrics.db
      SERVER_PORT: "8090"
      SPRING_FREEMARKER_CACHE: "false"
      SPRING_FREEMARKER_TEMPLATE_LOADER_PATH: file:/app/templates
      SPRING_SERVLET_MULTIPART_LOCATION: /app/dropbox
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: file:/app/static
      UPLOAD_SIMPLE_DATASTORE: /var/ceh-catalogue/datastore
      LEGILO_URL: http://legilo:8000
      LEGILO_USER: user
      LEGILO_PASSWORD: password
      FUSEKI_SPARQL_ENDPOINT: http://fuseki:3030/ds/sparql
      FUSEKI_DATASET_URL: http://fuseki:3030/ds
      SPRING_PROFILES_ACTIVE: development,server-eidc,search-basic,cache,service-agreement,upload-simple
    env_file:
      - path: secrets.env
        required: false
      - path: override.env
        required: false
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - solr
    develop:
      watch:
        - action: rebuild
          path: ./build.gradle
        - action: rebuild
          path: ./gradle/libs.versions.toml
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./docker/entrypoint-dev.sh
  web:
    image: node:22-alpine
    working_dir: /app/web
    volumes:
      - ./web:/app/web
    command: sh -c "npm install && (npm run watch & npm run watch-css)"
volumes:
  dropbox:
  mapfiles:
  datastore:
  gradle-cache:
