services:
  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
  web:
    build: .
    depends_on:
      - solr
    volumes:
      # Create a **docker-compose.override.yml** file, copy these volumes and uncomment
      # directories needed for development.
      # Uncomment to see catalogue json files
      #- ./datastore:/var/ceh-catalogue/datastore
      # Uncomment to see Hubbub Upload uploaded files
      - dropbox:/var/ceh-catalogue/dropbox
      - mapfiles:/var/ceh-catalogue/mapfiles
      # Uncomment to see Simple Upload uploaded files
      #- ./upload:/var/upload/datastore
      # Uncomment to work on XML schema validation in Docker container
      #- ./schemas:/opt/ceh-catalogue/schemas
      # Uncomment to work on Freemarker templates in Docker container
      #- ./templates:/opt/ceh-catalogue/templates
      # Uncomment to work on styling (LESS) & javascript in Docker container
      #- ./web/src:/opt/ceh-catalogue/static
      # Uncomment to work on webpack
      # Run 'npm run watch' and connect to the catalogue docker service to have code recompiled while developing
      # Then use the services tab in IntelliJ
      #- ./web/dist:/opt/ceh-catalogue/static/scripts
      # Uncomment when enabling 'metrics' profile for local sqlite database, if needed update the permissions on the metrics-db folder so sqlite can write to it: 'chmod a+w metrics-db'
      #- ./metrics-db:/var/ceh-catalogue/metrics-db/
    environment:
      - documents.baseUri=http://localhost:8080
      - doi.api=https://api.test.datacite.org/dois
      - hubbub.url=http://hubbub:8080/v7
      - spring.freemarker.cache=false
      - spring.profiles.active=development,upload:simple,server:eidc,search:basic,service-agreement
      - jira.serviceAgreement.prefix=CT-
    env_file:
      - secrets.env
  solr:
    build: "solr"
    ports:
      - "8983:8983"
  mapserver:
    image: registry.gitlab.ceh.ac.uk/eip/mapserver:2
    ports:
      - "9000:80"
    volumes:
      - mapfiles:/mapserver/maps
      - ./fixtures/mapserver-data:/mapserver/data

volumes:
  dropbox:
  mapfiles:
