version: "3.7"
services:
  web:
    build: .
    depends_on:
      - solr
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Create a docker-compose.override.yml file, copy these volumes and uncomment
      # directories needed for development.
      # Uncomment to see catalogue json files
      #- ./datastore:/var/ceh-catalogue/datastore
      # Uncomment to see Hubbub Upload uploaded files
      - dropbox:/var/ceh-catalogue/dropbox
      - mapfiles:/var/ceh-catalogue/mapfiles
      # Uncomment to see Simple Upload uploaded files
      #- ./upload:/var/upload/datastore
      # Uncomment to work on XML schema validation in Docker container
      #- ./schemas:/opt/ceh-catalogue/schemas
      # Uncomment to work on Freemarker templates in Docker container
      #- ./templates:/opt/ceh-catalogue/templates
      # Uncomment to work on styling (LESS) & javascript in Docker container
      #- ./web/src:/opt/ceh-catalogue/static
    environment:
      - doi.api=https://api.test.datacite.org/dois
      - hubbub.url=http://hubbub/
      - jira.jqlTemplate=project=ct and labels={id}
      - spring.freemarker.cache=false
      - spring.profiles.active=development,upload:simple
    env_file:
      - secrets.env
  solr:
    build: "solr"
    ports:
      - "8983:8983"
  mapserver:
    image: registry.gitlab.ceh.ac.uk/eip/mapserver:2
    ports:
      - "9000:80"
    volumes:
      - mapfiles:/mapserver/maps
      - ./fixtures/mapserver-data:/mapserver/data

volumes:
  dropbox:
  mapfiles:
