version: "3"
services:
  web:
    build: .
    depends_on:
      - solr
      - mapserver
    ports:
      - "8080:8080"
    volumes:
      - ./dropbox:/var/ceh-catalogue/dropbox
      - ./upload:/var/upload/datastore
      - mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      - doi.api=https://api.test.datacite.org/dois
      - jira.address=https://jira-test.nerc-lancaster.ac.uk/rest/api/2
      - spring.profiles.active=development,upload:simple
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    image: registry.gitlab.ceh.ac.uk/eip/mapserver:2
    volumes:
      - mapfiles:/mapserver/maps
      - ./fixtures/mapserver-data:/mapserver/data

volumes:
  mapfiles:
