version: "3"
services:
  web:
    ports:
      - "8080:8080"
    # Mount working directories for development
    volumes:
      - ./schemas:/opt/ceh-catalogue/schemas
      - ./templates:/opt/ceh-catalogue/templates
      - ./web/src:/opt/ceh-catalogue/web
      - ./java/build/libs:/opt/ceh-catalogue/libs
    environment:
      - doi.api=https://api.test.datacite.org/dois
      - spring.profiles.active=development,upload:simple
      - jira.address=https://jira-test.nerc-lancaster.ac.uk/rest/api/2
  solr:
    # Expose the solr port for development
    ports:
      - "8983:8983"

  mapserver:
    # Expose mapserver port during development
    ports:
      - "9000:80"
