version: "2"
services:
  web:
    ports:
      - "8080:8080"
    # Mount working directories for development
    volumes:
      - ./datastore:/var/ceh-catalogue/datastore
      - ./schemas:/opt/ceh-catalogue/schemas
      - ./templates:/opt/ceh-catalogue/templates
      - ./web/src:/opt/ceh-catalogue/web
      
  solr:
    # Expose the solr port for development
    ports:
      - "7000:8080"

  mapserver:
    # Mount working directories for mapserver
    volumes:
      - ./mapserver/helpers:/mapserver/helpers
      - ./fixtures/mapserver-data:/mapserver/data
    # Expose mapserver port during development
    ports:
      - "9000:80"
