version: "3"
services:
  web:
    # Mount working directories for development
    volumes:
      - ./schemas:/opt/ceh-catalogue/schemas
      - ./templates:/opt/ceh-catalogue/templates
      - ./web/src:/usr/local/tomcat/webapps/ROOT/static
  solr:
    # Expose the solr port for development
    ports:
      - "8983:8983"

  mapserver:
    # Expose mapserver port during development
    ports:
      - "9000:80"
