version: "3"
services:
  web:
    build: .
    depends_on:
      - solr
      - mapserver
    ports:
      - 8080
    volumes:
      - ./datastore:/var/ceh-catalogue/datastore
      - ./supporting-documents:/var/ceh-catalogue/supporting-documents
      - ./dropbox:/var/ceh-catalogue/dropbox
      - ./eidchub-rw:/var/ceh-catalogue/eidchub-rw
      - mapfiles:/var/ceh-catalogue/mapfiles
    environment:
      - spring.profiles.active=development
    env_file:
      - secrets.env
  solr:
    build: "solr"
  mapserver:
    image: registry.gitlab.ceh.ac.uk/eip/mapserver:2
    volumes:
      - mapfiles:/mapserver/maps
      - ./fixtures/mapserver-data:/mapserver/data

volumes:
  mapfiles: