source 'https://rubygems.org'

gem 'rake'
gem 'parallel_tests'
gem 'rspec-retry'
gem 'rspec'
gem 'json'
gem 'rdf-rdfxml'
gem 'capybara'
gem 'nokogiri'
gem 'rest-client'
gem 'rspec_junit_formatter'
gem 'selenium-webdriver'
gem 'equivalent-xml'
