<div class="footer footer-ri hidden-print clearfix">
    <div class="footer-curve"></div>
    <div class="footer-content">
    <div class="container">
        <div class="footergrid">
            <div class="logo">
                <a href="https://www.ceh.ac.uk/" aria-label="Go to Home page">
                <img src="https://www.ceh.ac.uk/sites/default/files/images/theme/ukceh_logo_long_720x170_white.png" />
                </a><br>&copy; UK Centre for Ecology &amp; Hydrology
            </div>
            <div class="socials">
                <a href="https://www.ceh.ac.uk/about-us/contact-us" class="social">
                    <i class="fas fa-xl fa-fw fa-phone"></i>
                </a>
                <a target="_blank" href="https://www.ceh.ac.uk/about-us/contact-us" aria-label="Email us" class="social">
                    <i class="fas fa-xl fa-fw fa-envelope"></i>
                </a>
                <a class="social" target="_blank" href="https://www.linkedin.com/company/uk-centre-for-ecology-hydrology/"aria-label="Go to our Linkedin">
                    <i class="fab fa-xl fa-fw fa-linkedin-in"></i>
                </a>
                <a class="social" target="_blank" href="https://twitter.com/@UK_CEH" aria-label="Go to our Twitter">
                    <i class="fab fa-xl fa-fw fa-twitter"></i>
                </a>
                <a class="social" target="_blank" href="https://www.facebook.com/UKCentreforEcologyandHydrology" aria-label="Go to our Facebook">
                    <i class="fab fa-xl fa-fw fa-facebook-f"></i>
                </a>
                <a class="social" target="_blank" href="https://www.youtube.com/UKCentreforEcologyHydrology" aria-label="Go to our YouTube">
                    <i class="fab fa-xl fa-fw fa-youtube"></i>
                </a>
            </div>
            <div class="menu">
                <a href="https://www.ceh.ac.uk/privacy-notice">Privacy notice</a>
                <a href="https://www.ceh.ac.uk/terms-of-use">Terms of use</a>
                <a href="https://www.ceh.ac.uk/about-us/contact-us">Contact</a>
                <a href="https://www.ceh.ac.uk/accessibility-statement">Accessibility</a>
            </div>
        </div>
    </div>
    </div>
</div>