<div class="metadataMenu" role="navigation">
    <a href="#">Description</a>
    <#if showCapabilities?? && showCapabilities = 1>
        <a href="#Capabilities">Capabilities</a>
    </#if>
    <#if showLifecycle?? && showLifecycle = 1>
        <a href="#Lifecycle">Lifecycle</a>
    </#if>
    <#if showUniqueness?? && showUniqueness = 1>
        <a href="#Uniqueness">Uniqueness</a>
    </#if>
    <#if showUsers?? && showUsers = 1>
        <a href="#Users">Users</a>
    </#if>
</div>