-- The metrics schema (#235). Flyway owns it from here on: JDBCMetricsService runs no DDL.
--
-- Applied by MetricsSchemaMigrator, never by Spring Boot's Flyway auto-configuration -- see that class.
-- Also run against H2 by JDBCMetricsServiceTest, so it sticks to SQL that PostgreSQL and H2 both accept:
-- an identity column rather than bigserial (equivalent on PostgreSQL), and IF [NOT] EXISTS throughout.
--
-- Written to be safe on a database that already holds the tables the pre-Flyway service created
-- (staging/dev environments that ran #234): MetricsSchemaMigrator baselines such a database at version 0
-- (not 1, unlike SQLite), so this script still runs there, and every statement below is a no-op where
-- its object already exists.
--
-- PRIMARY KEY: a surrogate id, not a natural key on (document, start_timestamp). The natural key cannot
-- hold yet -- lastRun starts at 0, so the first sync after every restart writes a (document, 0) window and
-- the same pair recurs across restarts (#248). syncDB therefore keeps inserting; whether it should upsert
-- is #238's decision, and the natural key can be added as a unique constraint once #248 is fixed.
--
-- TIMESTAMPS: epoch seconds as bigint. integer is 32-bit on PostgreSQL and overflows in January 2038;
-- SQLite's flexible integer affinity hid that. Converting to timestamptz is #244, deliberately not here,
-- so the #236 data migration stays a straight value-for-value copy.

CREATE TABLE IF NOT EXISTS views (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_timestamp bigint  NOT NULL,
    end_timestamp   bigint  NOT NULL,
    amount          integer NOT NULL,
    document        text    NOT NULL,
    doc_title       text    NOT NULL,
    record_type     text    NOT NULL
);

CREATE TABLE IF NOT EXISTS downloads (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_timestamp bigint  NOT NULL,
    end_timestamp   bigint  NOT NULL,
    amount          integer NOT NULL,
    document        text    NOT NULL,
    doc_title       text    NOT NULL,
    record_type     text    NOT NULL
);

-- Tables created by the pre-Flyway service have no id. Skipped (with a notice) where it already exists.
ALTER TABLE views     ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE downloads ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Per-document totals, read while every record page renders:
--   SELECT coalesce(sum(amount), 0) FROM views WHERE document = ?
-- Composite on (document, amount), matching what #242 shipped on SQLite -- NOT document alone. amount is
-- what makes it covering: the sum comes straight off the index without visiting the table. A plain
-- document index would leave PostgreSQL slower than the SQLite schema it replaces. Same names as #242.
CREATE INDEX IF NOT EXISTS idx_views_document_amount     ON views     (document, amount);
CREATE INDEX IF NOT EXISTS idx_downloads_document_amount ON downloads (document, amount);

-- Metrics report (GET /{catalogue}/metrics), date-range filter:
--   start_timestamp >= ? AND end_timestamp <= ?
-- start_timestamp leads because it is the selective bound (recent windows); end_timestamp rides along
-- so its filter is checked in the index rather than on the heap. An end-only filter selects most of
-- the table, so it gets no index of its own.
CREATE INDEX IF NOT EXISTS idx_views_start_end     ON views     (start_timestamp, end_timestamp);
CREATE INDEX IF NOT EXISTS idx_downloads_start_end ON downloads (start_timestamp, end_timestamp);

-- Metrics report, record_type IN (...), usually alongside the start date. record_type alone has only a
-- handful of values, so it leads a composite with start_timestamp rather than standing alone.
CREATE INDEX IF NOT EXISTS idx_views_record_type_start     ON views     (record_type, start_timestamp);
CREATE INDEX IF NOT EXISTS idx_downloads_record_type_start ON downloads (record_type, start_timestamp);

-- Deliberately no index for the report's document filter. It is lower(document) LIKE lower('%...%'):
-- a leading wildcard, which no b-tree can satisfy however it is built. That filter needs redesigning,
-- not indexing -- see #243.
