<div class="footer footer-ukceh d-print-none clearfix">
  <div class="container">

    <div class="footer-logos">
      <div><a href="https://www.ceh.ac.uk" target="_blank" target="_blank" rel="noopener noreferrer">Hosted by <img src="/static/img/ukceh_logo_mono.png" alt="UKCEH logo" title="UKCEH"></a></div>
      <div><a href="https://eds.ukri.org/" target="_blank" target="_blank" rel="noopener noreferrer"><img src="https://eidc.ac.uk/sites/default/files/eidcImages/footer/NERC_EDS.png" alt="NERC EDS logo" title="NERC EDS"></a></div>
      <div><a href="https://eidc.ac.uk/coretrustseal" target="_blank" target="_blank" rel="noopener noreferrer"><img src="https://eidc.ac.uk/sites/default/files/eidcImages/footer/CoreTrustSeal.png" alt="CoreTrustSeal logo" title="CoreTrustSeal" ></a></div>
    </div>
    <div class="footer-links" role="contentinfo">
      <a href="https://eidc.ac.uk/accessibility">Accessibility</a>
      <a href="https://eidc.ac.uk/policies/privacy" target="_blank" rel="noopener noreferrer">Privacy</a>
      <a href="https://eidc.ac.uk/policies/terms">Terms of use</a>
      <a href="https://eidc.ac.uk/contact">Contact</a>

    </div>
    <div class="footer-socials">
      <a target="_blank" href="https://eidc.ac.uk/contact" aria-label="Contact us" class="social">
          <i class="fa-solid fa-xl fa-fw fa-envelope"></i>
      </a>
      <a class="social" target="_blank" href="https://twitter.com/EIDC_data" aria-label="Go to our X (Twitter) feed">
          <i class="fa-brands fa-xl fa-fw fa-x-twitter"></i>
      </a>
    </div>
    <div class="footer-terms">
      UKCEH &copy; ${.now?datetime?string['yyyy']}
    </div>

  </div>
</div>
