<div class="footer footer-ukceh pt-3 d-print-none clearfix">
  <div class="container">

    <div class="footer-logos">
      <div>
        <a href="https://www.ceh.ac.uk" target="_blank" target="_blank" rel="noopener noreferrer">
          <img class="logo-ukceh" src="/static/img/ukceh.svg" alt="UKCEH logo" title="UKCEH">
        </a>
      </div>
    </div>
    <div class="footer-links" role="contentinfo">
      <a href="https://www.ceh.ac.uk/privacy-notice">Privacy notice</a>
      <a href="https://www.ceh.ac.uk/terms-of-use">Terms of use</a>
      <a href="https://www.ceh.ac.uk/about-us/contact-us">Contact</a>
      <a href="https://www.ceh.ac.uk/accessibility-statement">Accessibility</a>
    </div>
    <div class="footer-socials">
      <a href="https://www.ceh.ac.uk/about-us/contact-us" class="social">
          <i class="fa-solid fa-xl fa-phone"></i>
      </a>
      <a target="_blank" href="https://www.ceh.ac.uk/about-us/contact-us" aria-label="Email us" class="social">
          <i class="fa-solid fa-xl fa-envelope"></i>
      </a>
      <a class="social" target="_blank" href="https://www.linkedin.com/company/uk-centre-for-ecology-hydrology/"aria-label="Go to our Linkedin">
          <i class="fa-brands fa-xl fa-linkedin-in"></i>
      </a>
      <a class="social" target="_blank" href="https://bsky.app/profile/ukceh.bsky.social" aria-label="Bluesky">
          <i class="fa-brands fa-xl fa-bluesky"></i>
      </a>
      <a class="social" target="_blank" href="https://www.facebook.com/UKCentreforEcologyandHydrology" aria-label="Go to our Facebook">
          <i class="fa-brands fa-xl fa-facebook-f"></i>
      </a>
      <a class="social" target="_blank" href="https://www.youtube.com/UKCentreforEcologyHydrology" aria-label="Go to our YouTube">
          <i class="fa-brands fa-xl fa-youtube"></i>
      </a>
    </div>
    <div class="footer-terms">
      UKCEH &copy; ${.now?datetime?string['yyyy']}
    </div>

  </div>
</div>
