<div class="footer footer-ukeof pt-3 d-print-none clearfix">
  <div class="container">

    <div class="footer-logos">
      <div><a href="https://www.ceh.ac.uk" target="_blank" target="_blank" rel="noopener noreferrer">Hosted by <img src="/static/img/ukceh.svg" class="logo-ukceh" alt="UKCEH logo" title="UKCEH" ></a></div>
    </div>
    <div class="footer-links" role="contentinfo">
      <a target="_blank" href="https://ukeof.org.uk/node/18" >Contact us</a>
      <a href="https://ukeof.org.uk/privacy">Privacy notice</a>
      <a href="https://ukeof.org.uk/terms-of-use">Terms of use</a>
    </div>
    <div class="footer-socials">
      <a target="_blank" href="https://ukeof.org.uk/node/18" aria-label="Contact us" class="social">
          <i class="fa-solid fa-xl fa-phone"></i>
      </a>

      <a target="_blank" href="https://ukeof.us4.list-manage.com/subscribe?u=8db0bba9a5434ccfcddf25ba2&id=b0a4fe2e59" aria-label="Subscribe" class="social">
          <i class="fa-solid fa-xl fa-envelope"></i>
      </a>

      <a class="social" target="_blank" href="https://bsky.app/profile/ukeof.bsky.social" aria-label="Bluesky">
          <i class="fa-brands fa-xl fa-bluesky"></i>
      </a>

      <a class="social" target="_blank" href="https://wakelet.com/@UKEOF" aria-label="Wakelet">
          <i class="fa-solid fa-xl fa-w"></i>
      </a>
    </div>
    <div class="footer-terms">
      <a href="https://creativecommons.org/licenses/by/4.0/" rel="noopener noreferrer"><small>This information is available under a Creative Commons Attribution-Share Alike 4.0 International license (CC BY-SA 4.0)</small></a>
    </div>

  </div>
</div>
