<div class="container">
  <div>Working collaboratively to maximise the value of the UK’s environmental observations</div>

  <div class="footerLinks">
    <a href="https://www.ukeof.org.uk/privacy-cookies">Privacy & Cookies</a>
    <a href="https://www.ukeof.org.uk/contact">Contact us</a>
    <a href="https://twitter.com/UKEnvObs/"><i class="fa-brands fa-fw fa-twitter" title="follow us on Twitter"></i></a>
    <a href="https://ukeof.us4.list-manage.com/subscribe?u=8db0bba9a5434ccfcddf25ba2&id=b0a4fe2e59">Subscribe to Newsletter</a>
  </div>

  <div>
    <a href="https://creativecommons.org/licenses/by/4.0/" rel="noopener noreferrer"><small>This information is available under a Creative Commons Attribution-Share Alike 4.0 International license (CC BY-SA 4.0)</small></a>
  </div>
</div>

