<#import "../skeleton.ftlh" as skeleton>

<@skeleton.master title="Thanks" catalogue=catalogues.defaultCatalogue()>
  <div class="container">
    <h1 class="mt-5 mb-4 display-4">Thank you</h1>
    <p>We'll review your details and someone will be in contact with you soon to discuss next steps.</p>
    <p>In the meantime, if you need any help, please <a href="mailto:info@eidc.ac.uk">email info@ceh.ac.uk</a></p>
  </div>
</@skeleton.master>
