<#import "../skeleton.ftlh" as skeleton>

<@skeleton.master title="Deposit request" catalogue=catalogues.defaultCatalogue()>
  <div class="container">
    <h1 class="pt-5 mb-4 display-4">EIDC deposit request</h1>
    <p>To deposit resources such as datasets,
    information products and model output data to the EIDC, we ask you to complete a short form. We don't ask for a lot of information and it should only take a few minutes.</p>
    <p>To get started, please <a href="/sso/login?success=../deposit-request">login</a>.  If you don't have an account, please <a href="/sso/signup">register</a>.</p>
    <p>For more information and help on preparing your resource for deposit see <a href="https://eidc.ac.uk/deposit/preparingData" target="_blank" rel="noopener noreferrer">our guidance</a>.</p>
  </div>
</@skeleton.master>
