package uk.ac.ceh.gateway.catalogue.indexing;

import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import uk.ac.ceh.gateway.catalogue.ef.Facility;
import uk.ac.ceh.gateway.catalogue.ef.Geometry;
import uk.ac.ceh.gateway.catalogue.services.SolrGeometryService;

import java.util.Arrays;

import static uk.ac.ceh.gateway.catalogue.indexing.SolrIndexMetadataDocumentGenerator.grab;

/**
 * Adds Facility specific details to a SolrIndex generated by an instance of
 * SolrIndexBaseMonitoringTypeGenerator
 * @author cjohn
 */
@Service
@AllArgsConstructor
public class SolrIndexFacilityGenerator implements IndexGenerator<Facility, SolrIndex> {
    private final SolrIndexBaseMonitoringTypeGenerator metadataDocumentSolrIndex;
    private final SolrGeometryService geometryService;
    
    @Override
    public SolrIndex generateIndex(Facility ef) {     
        return metadataDocumentSolrIndex
                .generateIndex(ef)
                .addLocations(geometryService.toSolrGeometry(grab(Arrays.asList(ef.getGeometry()), Geometry::getValue)));
    }    
}
