[#ftl]
WEB
  IMAGEPATH "/ms4w/tmp/ms_tmp/"
  IMAGEURL  "/ms_tmp/"
  METADATA
    "wms_onlineresource"               "${mapServerDetails.getWmsUrl(doc.id)}"
    "wms_inspire_capabilities"         "url"
    "wms_languages"                    "eng"
    "wms_inspire_metadataurl_href"     "${doc.uri}"
    "wms_inspire_metadataurl_format"   "application/vnd.iso.19139+xml"
    "wms_title"                        "${doc.title}"
    "wms_abstract"                     "${doc.description!''}"
    "wms_keywordlist"                  "${geminiHelper.getKeywords(doc)?join(',')}"
    "wms_keywordlist_vocabulary"       "ISO"
    "wms_keywordlist_ISO_items"        "infoMapAccessService"
    "wms_contactperson"                ""
    "wms_contactorganization"          "Environmental Information Data Centre"
    "wms_contactposition"              "pointOfContact"
    "wms_addresstype"                  "Postal"
    "wms_address"                      "UK Centre for Ecology & Hydrology, Lancaster Environment Centre, Library Avenue, Bailrigg"
    "wms_city"                         "Lancaster"
    "wms_stateorprovince"              "Lancashire"
    "wms_postcode"                     "LA1 4AP"
    "wms_country"                      "UK"
    "wms_contactvoicetelephone"        ""
    "wms_contactfacsimiletelephone"    ""
    "wms_contactelectronicmailaddress" "info@eidc.ac.uk"
    "wms_accessconstraints"            "[#if accessConstraints??]${doc.accessConstraints?first.value}[#else]None[/#if]"
    "wms_fess"                         "None"
    "wms_enable_request"               "GetCapabilities GetMap GetLegendGraphic GetFeatureInfo"
    "wms_getmap_formatlist"            "image/jpeg,image/tiff,image/png"
    "wms_srs"                          "CRS:84 EPSG:4326 EPSG:3857 EPSG:3035 EPSG:27700 EPSG:4258"
    "wms_bbox_extended"                "true"
    "wms_style_name"                   "inspire_common:DEFAULT"
    "wms_style_title"                  "inspire_common:DEFAULT"
    "wms_sld_enabled"                  "false"
    "wms_getfeatureinfo_formatlist"    "text/xml,application/json"
  END
END
