# suppress inspection "UnusedProperty" for whole file
# suppress inspection "HttpUrlsUsage" for whole file
# suppress inspection "SpringBootApplicationProperties" for whole file
spring.security.oauth2.client.registration.cognito.client-id=get_from_aws_client_id
spring.security.oauth2.client.registration.cognito.redirect-uri=${documents.baseUri}/login/oauth2/code/cognito
spring.security.oauth2.client.registration.cognito.client-authentication-method=none
spring.security.oauth2.client.registration.cognito.scope=openid
spring.security.oauth2.client.provider.cognito.issuerUri=get_from_aws_issuer_uri
spring.security.oauth2.client.provider.cognito.user-name-attribute=username
aws.cognito.userpool.domain=get_from_aws_userpool_domain
aws.cognito.userpool.id=get_from_aws_userpool_id
aws.cognito.client.logout.redirect-uri=${documents.baseUri}/eidc/documents
