# suppress inspection "UnusedProperty" for whole file
# suppress inspection "HttpUrlsUsage" for whole file
# suppress inspection "SpringBootApplicationProperties" for whole file
access-button.collection.link=/explore/data
crowd.address=https://crowd.ceh.ac.uk/crowd/rest/usermanagement/latest
crowd.username=eip-ro
data.repository.location=/var/ceh-catalogue/datastore
datalabs.cookieName=authorization
datalabs.issuer=https//datalabs.datalabs.ceh.ac.uk
datalabs.remoteJwks=https://mjbr.eu.auth0.com/.well-known/jwks.json
datalabs.users=http://datalab-api-service:8000/api?query={users{userId,name}}
datalabs.userPermissions=http://datalab-api-service:8000/api?query={userPermissions}
documents.baseUri=https://catalogue.ceh.ac.uk
doi.api=https://api.datacite.org/dois
doi.prefix=10.5285
doi.publisher=NERC EDS Environmental Information Data Centre
doi.legacyPublisher=NERC Environmental Information Data Centre
doi.username=BL.NERC
download.url.regexOrder=https://order-eidc\\.ceh\\.ac\\.uk/resources/.{8}/order\\?*.*
download.url.regexPackage=https://data-package\\.ceh\\.ac\\.uk/.*
download.url.regexDatastore=https://catalogue\\.ceh\\.ac\\.uk/datastore/eidchub/.*
download.url.regexCeda=https://data\\.ceda\\.ac\\.uk/eidc/.*
download.url.regexSupportingDocs=https://data-package\\.ceh\\.ac\\.uk/sd/.*
download.url.regexOrderManDownload=http(s?)://catalogue\\.ceh\\.ac\\.uk/download\\?fileIdentifier=.*
fuseki.catalogueIds=eidc,ukeof,ukceh
fuseki.sparqlEndpoint=https://sparql.catalogue.ceh.ac.uk/ds/sparql
fuseki.datasetUrl=https://sparql.catalogue.ceh.ac.uk/ds
fuseki.username=admin
gemet.concepturl=https://www.eionet.europa.eu/gemet/getConceptsMatchingRegexByThesaurus?regex=^&thesaurus_uri=http://www.eionet.europa.eu/gemet/concept/&language=en
gemet.local=/var/ceh-catalogue/vocabs/gemet.json
hubbub.location=/var/ceh-catalogue/dropbox
hubbub.url=https://hubbub.ceh.ac.uk/v7
hubbub.username=eidc_hubbub
hubbub.request.pagesize=100000
jena.location=/var/ceh-catalogue/tdb
jira.address=https://jira.ceh.ac.uk/rest/api/2/
jira.depositRequest.project=EIDCHELP
jira.jqlTemplate=project=eidchelp AND component='data transfer' AND cf[13250]={id}
jira.username=eidc_ingest
jira.serviceAgreement.prefix=EIDCHELP-
legilo.url=https://legilo.eds-infra.ceh.ac.uk
legilo.user=eidc_hubbub
logging.level.root=warn
management.endpoints.web.exposure.include=health,loggers,prometheus
management.server.port=8081
maps.location=/var/ceh-catalogue/mapfiles
mapserver.url=http://mapserver/mapserver/{id}
mapserver.camptocamp=true
serviceagreement.start=2021-12-20
solr.server.url=http://solr:8983/solr
ukceh.sparql.endpoint=https://vocabs.ceh.ac.uk/fuseki/skosmos/query
spring.freemarker.cache=true
spring.freemarker.check-template-location=false
spring.freemarker.settings.date_format=yyyy-MM-dd
spring.freemarker.settings.template_exception_handler=rethrow
spring.freemarker.template-loader-path=file:/opt/ceh-catalogue/templates
spring.web.error.whitelabel.enabled=false
spring.web.error.include-message=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false
spring.jackson.default-property-inclusion=non_empty
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=file:/opt/ceh-catalogue/static/
spring.servlet.multipart.location=/var/ceh-catalogue/dropbox
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
upload.simple.datastore=/var/upload/datastore
metrics.database.url=jdbc:sqlite:/var/ceh-catalogue/metrics-db/metrics.db
metrics.users.excluded=dgwr,kath,phtr,rstu,hajd,matnic,jenroe,jashun,simgil,tinzha,elsdhi,shofer,rafbar,katwri,crimar,leav,shar1,glenn,clwe,margla
ror.url.dataDump=https://zenodo.org/api/communities/ror-data/records?q=&sort=newest
ror.local=/var/ceh-catalogue/ror
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=uk.ac.ceh.gateway.catalogue.search,uk.ac.ceh.gateway.catalogue.sparql,uk.ac.ceh.gateway.catalogue.wellknown
